# Generated by Django 5.0.5 on 2024-05-08 04:17

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.IntegerField(blank=True, null=True)),
                ('applicant', models.CharField(blank=True, max_length=500, null=True)),
                ('facility_type', models.CharField(blank=True, max_length=200, null=True)),
                ('cnn', models.IntegerField(blank=True, null=True)),
                ('location_description', models.CharField(blank=True, max_length=500, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('blocklot', models.CharField(blank=True, max_length=200, null=True)),
                ('block', models.CharField(blank=True, max_length=200, null=True)),
                ('lot', models.CharField(blank=True, max_length=200, null=True)),
                ('permit', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('foodItems', models.CharField(blank=True, max_length=1000, null=True)),
                ('x', models.FloatField(blank=True, null=True)),
                ('y', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('schedule', models.CharField(blank=True, max_length=1000, null=True)),
                ('dayshours', models.CharField(blank=True, max_length=200, null=True)),
                ('noi_sent', models.CharField(blank=True, max_length=200, null=True)),
                ('approved', models.CharField(blank=True, max_length=200, null=True)),
                ('received', models.IntegerField(blank=True, null=True)),
                ('prior_permit', models.IntegerField(blank=True, null=True)),
                ('expiration_date', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('fire_prevention_districts', models.IntegerField(blank=True, null=True)),
                ('police_districts', models.IntegerField(blank=True, null=True)),
                ('supervisor_districts', models.IntegerField(blank=True, null=True)),
                ('zip_codes', models.IntegerField(blank=True, null=True)),
                ('neighborhoods_old', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
